### ISSUE TITLE
Missing rubrical in generated service book

### ISSUE THREAD

**Issue by paulvickers** [mcolburn/durham#79]
Lines 801–805 of index.html contain the following:
````
<!-- Then on all days rubric PV 20230225 -->
<tr>
<td class='leftCell'><p class='mixed'><span class='rubric'><span class='kvp' data-key='pub.priest.servicebook_gr_GR_cog|li.rubric.alldays'>Εἶτα κατὰ <span class='boldred'>πᾶσαν</span> Λειτουργἰαν· </span>
</span></p></td>
<td class='rightCell'><p class='mixed'><span class='rubric'><span class='kvp' data-key='pub.priest.servicebook_en_UK_durlash|li.rubric.alldays'>Then, on <span class='boldred'>all</span> days:</span></span>
</p></td>
````

This creates a rubrical 'Then, on all days:'. I can see this when editing in both the the en_uk_durlash:
![Screenshot 2023-08-08 at 15 58 22](https://github.com/mcolburn/durham/assets/4840626/19d8fad1-ef9d-4b4e-ab4b-2d3744c6687f)

And in the Romanian ro_uk_dur:
![Screenshot 2023-08-08 at 15 58 43](https://github.com/mcolburn/durham/assets/4840626/831e1b8b-880c-4a8b-84b6-5e14e8b2efe3)

But when I generate the service book this directive is missing:
![Screenshot 2023-08-08 at 15 58 33](https://github.com/mcolburn/durham/assets/4840626/9a5e01c0-3f80-4c7d-9c6c-0a3245a73b4d)

Could this be because there is no corresponding directive in any other English version in the database?

**Comment by paulvickers** [comment]
Nevermind. It appears to be there now. Possibly because I found a mismatched kvp in a left and right cell further down?

**Comment by mcolburn** [comment]
The problem appears to be that the generated html has another span embedded where the text of the rubric appears.  

<img width="483" alt="image" src="https://github.com/mcolburn/durham/assets/1334217/16601b44-4c7b-4459-88c2-72e8dec679df">

This happens for Greek, English, and the Romanian:

<img width="958" alt="Pasted Graphic 1" src="https://github.com/mcolburn/durham/assets/1334217/7d414208-e096-4fe7-8b6f-b6aa38b5548a">

I have checked and there is no key called y.m.d.md.

The only thing I can think of is that the generator is trying to compute a lookup key.  The keys in the topic calendar are values such as y2018.m01.d02.ymd.  Even if the generator is trying to compute a key and returning it without numbers, it would be y.m.d.ymd not y.m.d.md.  

The only way to solve this issue is to fire up the dev environment and turn on the debugger.

**Comment by paulvickers** [comment]
That's weird, as that's not something I've added to the service. It's not a deal breaker as I can just add it to the generated .tex file post hoc.

**Comment by mcolburn** [comment]
Warning -- I found the bug and I am about to restart OLW.

**Comment by mcolburn** [comment]
I pushed the fix and restarted the server.

Now when I generate, I get this:

<img width="817" alt="image" src="https://github.com/mcolburn/durham/assets/1334217/0a2556f1-d5ad-41a4-93e5-ac9bdd5c5ec8">

Please verify and close.  Thanks!

**Comment by paulvickers** [comment]
Thanks!

**Comment by mcolburn** [comment]
Glad to help!
